#### use COPY --from

# syntax=docker/dockerfile:1
FROM golang:1.23 AS build
WORKDIR /src
COPY main.go ./main.go
RUN go build -o /bin/hello ./main.go

FROM scratch
COPY --from=build /bin/hello /bin/hello
CMD ["/bin/hello"]


### Comaprison While using distroless multistage build and no multistage build ..using docker images
#REPOSITORY             TAG       IMAGE ID       CREATED         SIZE
#no_multistage          latest    9537bd7bccfd   7 minutes ago   870MB
#multistage_copy_from   latest    6cd23bb1f931   7 minutes ago   2.13MB
